version: '3'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
        SG_VERSION: $SG_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
    #networks:
    #  - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/lookups:/usr/share/logstash/lookups:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx4g -Xms4g"
    #networks:
    #  - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
        SG_VERSION_KIBANA: $SG_VERSION_KIBANA
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    #networks:
    #  - elk
    depends_on:
      - elasticsearch

  proxy:
    image: nginx:alpine
    ports:
        - 80:80
    volumes:
        # List all the servers that we want to proxy here
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/passwd:/etc/nginx/passwd

#networks:
#  elk:
#   driver: bridge
